### PR TITLE
Make difficulty values float64

### PR DESCRIPTION
**Pull request by christopher-dG**
This change is [Reviewable](https://reviewable.io/reviews/natsukagami/go-osu-parser/1)

### CODE REVIEW

**Comment by christopher-dG** [comment]
I'll need to update the tests, and probably add one for a beatmap with float values. I don't have time for a couple days though. Probably Sunday or Monday.

**Comment by natsukagami** [comment]
It's completely okay! I'm not really maintaining this code anymore.

This was written on the first days of learning Go, so the code quality will be very awful T_T

**Comment by christopher-dG** [comment]
Managed to squeeze those tests in before I left!

**Comment by natsukagami** [comment]
Thank you!

**Pull request merged**
